54 multiplier models
cooper-org/cooper pull request #66
Opened 2022-12-07 19:06 UTC by IsitaRex

Closes #54 
## Changes
On the multipliers module we created a new class called [cooper.multipliers.MultiplierModel](https://github.com/IsitaRex/cooper/blob/ff3d9e27f0d42ffb64c907a4486f1a74f57d8910/cooper/multipliers/multiplier_model.py), which predicts the value of the Lagrange multipliers associated with the equality or  inequality constraints of a [cooper.problem.ConstrainedMinimizationProblem](https://github.com/IsitaRex/cooper/blob/ff3d9e27f0d42ffb64c907a4486f1a74f57d8910/cooper/problem.py).
Additionally, we created a new Lagrangian formulation --> [cooper.formulation.LagrangianFormulation](https://github.com/IsitaRex/cooper/blob/ff3d9e27f0d42ffb64c907a4486f1a74f57d8910/cooper/formulation/lagrangian_model.py) that works with the created `MultiplierModel` class.

## Testing
We tested the class multipliers.MultiplierModel with the simplest model. A linear model with a single output.
The new Lagrangian Formulation was also tested.

## References
This idea comes from the [paper](https://proceedings.neurips.cc/paper/2020/hash/62db9e3397c76207a687c360e0243317-Abstract.html) by Narasimhan et al.  and we took their [repository](https://github.com/google-research/google-research/tree/master/many_constraints) as reference.

2022-12-08 18:05 UTC, daoterog requested changes

2022-12-08 18:05 UTC, daoterog commented on cooper/optim/constrained_optimizers/simultaneous_optimizer.py
> +        # TODO: Check if the isintance flag has to be added to other optimizers
Missing TODO

2022-12-08 18:05 UTC, daoterog commented on cooper/optim/constrained_optimizers/constrained_optimizer.py
> +        # TODO: ensure that the dual optimizer and the dual scheduler is initialized when LagrangeModelFormulation
Missing TODO

2022-12-08 18:05 UTC, daoterog commented on cooper/optim/constrained_optimizers/simultaneous_optimizer.py
> +        # TODO: Fill the flip dual gradients and model formulation flag with other optimizers
Missing TODO

2022-12-08 18:05 UTC, daoterog commented on cooper/formulation/lagrangian_model.py
> +            # new_loss.backward(inputs=dual_vars)
This alternative implementation should be disregarded, that implementation corresponds to confusion made while looking at the authors' code, it was a test. The current implementation is the one that works and should be kept.

2022-12-08 18:05 UTC, daoterog commented on cooper/formulation/lagrangian_model.py
> +            # TODO: document this
Is it really necessary to document this?

2025-03-28 16:12 UTC, merajhashemi commented
Addressed in #100.

2025-03-28 16:12 UTC, closed without merging